### PR TITLE
Updated version number to 3.9.0.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by mikeller** [comment]
@Daniel-1276: I am using a modified version of the configurator.
The plan was to stop distribution of the firmware embedded in the configurator through the Chrome web store, since Google has announced the end of support for Chrome web apps on non-chromebooks at the beginning of 2018. Unfortunately there still is a fair bit of work on the configurator left to get to this point, and I am struggling to find the time for this.

**Comment by Daniel-1276** [comment]
Hi Mike, is there a chance to get that modified version of the configurator you are currently using, or would you suggest going back to 3.8.9 ?

**Comment by Daniel-1276** [comment]
Yes, I did installed the "openlrsng-configurator 1.0 RC1" using alternative installation method. Should this s version also work for the 3.9.0 RC2 pre-release?

**Comment by mikeller** [comment]
That was just a test to test the GitHub release API.

Try installing https://github.com/openLRSng/openLRSng-configurator/archive/master.zip

**Comment by Daniel-1276** [comment]
Oh, how embarrassing ... I mean it's clearly mentioned in the instructions, to CLONE the repository. I was downloading from the releases ... damn ! Now it's working :-D Thank's for your kind support mike !

**Comment by mikeller** [comment]
You can actually also download the tip of the repository as a zip file - but cloning makes it easier if you want to follow the latest version...

**Pull request merged**
