### PR TITLE
Enable compile with PlatformIO and TravisCI

### PR DESCRIPTION
**Pull request by fiveangle**
-Move sources into 'src' dir
-Add support scripts
-Add PlatformIO config
-Add TravisCI config
-Modify Makefile to support "src" subdirectory

### CODE REVIEW

**Comment by fiveangle** [comment]
I had tossed this together for myself, and figured I'd submit here in case you want to enable, but I realize you mentioned re-arranging the hw platforms, so feel free to close if not interested.

**Comment by fiveangle** [comment]
I'm not at a system that can build avr projects with make right now, but I suspect the changes I added to Makefile might fix.  Do you mind giving it a shot ?

Regarding documentation, are you thinking on the openLRSngWiki repo ?

**Comment by mikeller** [comment]
@fiveangle:

Almost works:
```
diff --git a/Makefile b/Makefile
index 97ebb5b..a1385f7 100644
--- a/Makefile
+++ b/Makefile
@@ -153,7 +153,7 @@ OUT_FOLDER=out
 #
 # Target object files
 #
-OBJS=openLRSng.o $(ARDUINO_LIB_OBJS) $(LIBRARIES_FOLDER)/libcore.a
+OBJS=$(SOURCES_FOLDER)/openLRSng.o $(ARDUINO_LIB_OBJS) $(LIBRARIES_FOLDER)/libcore.a
 
 #
 # Default target
@@ -182,7 +182,7 @@ endef
 
 .PHONY: all clean upload astyle 433 868 915 allfw default
 
-$(SOURCES_FOLDER)/%.o: %.ino
+$(SOURCES_FOLDER)/%.o: $(SOURCES_FOLDER)/%.ino
        $(ino-command)
 
 $(SOURCES_FOLDER)/%.o: %.c
```

Re documentation, wiki sounds like a good place for it.

**Comment by fiveangle** [comment]
made those changes to Makefile

re: wiki - I've never used the GH wiki feature, but I can't even seem to find where the source for this page is even located:

https://github.com/openLRSng/openLRSngWiki/wiki/Building-OpenLRSng

Any pointers ?

**Comment by mikeller** [comment]
`make` works now. Thanks.

Good point about the wiki, it editing seems to be restricted to committers only. Given you access.

**Comment by csurf** [comment]
FYI, this breaks compilation with Arduino IDE due to fact that the .ino Arduino sketch file is no longer in a folder named `openLRSng`. We could add a symlink to the top-level folder named `openLRSng` that points to `src` so that Arduino IDE users can still compile without having to rename folders and/or move stuff around.

**Comment by mikeller** [comment]
Heh, I wasn't aware that matching names are a requirement. As an alternative, we could rename `src/` to `openLRSng/` to meet the requirements. (Also, before the move into `src/`, this would easily have been broken anyway, if users cloned the repository into a directory with a different name.)

**Comment by fiveangle** [comment]
That would work.  I had considered doing that in the first place but then for some reason went with “src” since it’s the default for PIO. 

I’ll make the change and test on ArduinoIDE and submit PR.

**Comment by fiveangle** [comment]
#170

btw- the benefit of PIO that I see isn't really for end-users to compile ATMega328 projects, but it is quite fast to compile these projects for Travis, PIO supports nearly every MCU under the sun so if the project moves to STM32 Travis will be ready while implementing native arduino-builder would only cover limited options, it allows a single build chain to support whatever direction the project goes for end-users too.  Once the hardware.h is broken up to be less of a monolithic, it will be relatively easy to add the necessary bits to Travis to auto-deploy releases right to the github page.  I could do it now, but would prefer to do after hardware.h is a bit tidier.

**Comment by csurf** [comment]
personally, kinda liked having it named sec, but Arduino complains.

Using a cloned repo in Windows maintains the repo name for the base folder, which in this case works (both repo and sketch file are named `openLRSng`).

It's true that if you download the repo as a zip file, it'll default to naming the directory as "repo-branch" (ex., openLRSng-master), so the extracted folder would need to be renamed anyway. However, now that it's in a sub-folder, the same would apply if the folder wasn't named "openLRSng".

I still compile with Arduino IDE, so the way I worked around this was that I added a hard directorysymlink (called a junction in windows) named `openLRSng` that points to `src`, and then added that symlink/directory to my got exclude file.

**Comment by mikeller** [comment]
> Using a cloned repo in Windows maintains the repo name for the base folder, which in this case works (both repo and sketch file are named openLRSng).

Even there, you can actually supply a name of your choice for the repo folder (and need to if you want to have multiple versions checked out in the same directory).

> I still compile with Arduino IDE, so the way I worked around this was that I added a hard directorysymlink (called a junction in windows) named openLRSng that points to src, and then added that symlink/directory to my got exclude file.

Not sure if symlinks are supported in git in a portable way, so that we could add the symlink to the repo - for now renaming the folder seems to be the most portable / least problem prone solution.

**Pull request merged**
