### PR TITLE
add component datasheets

### PR DESCRIPTION
**Pull request by csurf**
add datasheets & 'register calculator spreadsheets' for RFM module, and also ATMega328p datasheet

### CODE REVIEW

**Comment by mikeller** [comment]
Not sure if we want to keep copies of these in the repository:
- they are binary, so they just eat up space, and cannot leverage the capabilities of git;
- they are released and updated by 3rd parties, so keeping links to where the latest version can be downloaded is probably more practical.

**Comment by geofrancis** [comment]
3rd parties have a bad habbit of changing urls and removing things after a while.

**Comment by mikeller** [comment]
They are normally removed because they are superseded. Also, n.b. that it is against the law in some places to re-publish copyrighted materials after the copyright owner stopped making them publicly available.

I think these documents should better be kept in the wiki (if anything), instead of in the source repository.

**Comment by geofrancis** [comment]
yes I agree the wiki is probably the best place for it.

**Comment by csurf** [comment]
ok, I'll close this and move to the wiki

**Pull request closed without merging**
