### PR TITLE
Enable stringent CI checking

### PR DESCRIPTION
**Pull request by fiveangle**
-Set `CI` env var true for Travis
-Enable warnings-as-errors PIO global build option for Travis

### CODE REVIEW

**Comment by fiveangle** [comment]
If this isn't wanted anymore, let me know.

Thanks,

-=dave

**Comment by fiveangle** [comment]
@csurf I suspect Mike marked this "Approved" with expectation someone else would also review, and then merge (as an informal method to catch obvious mistakes that are sometimes overlooked by just a single reviewer).

Can you review and if you agree/approve, merge ?  Alternatively we can abandon flagging warnings as errors for CI, but I tend to agree with Mike that warnings are often early tips that somethings going a wrong direction and could use a correction earlier than later.

**Comment by csurf** [comment]
@fiveangle 
ok, just walk me through this as I'm new to travisCI. I'm seeing an error saying 'all checks have failed'. How do we fix? and, dumb question, but what does it mean ? (better yet, pls explain so that I can learn this stuff).

As soon as we get this cleared up, I will merge

**Comment by fiveangle** [comment]
First rule of reviewing any PR that touches continuous integration, is that you can never trust if it fails or not: you always have to check the build log to determine if the failure is expected, because CI changes often fall into the chick-egg problem.  This PR is one of those.

Yes, this build failed when I submitted it because your changes to RX.h were causing a slew of compile warnings on HEAD at the time.  This PR enables warnings-as-errors compile option for CI, so naturally those warnings would then turn into errors with this PR, resulting in failure, which would be expected, and would point to the need to fix your RX.h warnings (again, chicken-egg problem).

To review build log for CI, click the ✔️ or ❌ next to the commit hash (or click "details" in the build failure notice area).  In there you will see the old warnings from your RX.h changes, which you've since resolved.

Since you resolved those earlier compile warnings, this merge should pass CI tests now, but even if they weren't, the PR would still be good to merge, so that upstream failure could then be investigated.

-=dave

**Comment by csurf** [comment]
understood. thanks for the info & patience.

merging...

**Comment by mikeller** [comment]
@fiveangle: Sorry, I was away for the long weekend here. I approved this pull request, but did not merge since there were warnings in the build at the time, and I wanted to have them fixed before this was merged...

**Pull request merged**
