### PR TITLE
SBUS TX input: Get it working.

### PR DESCRIPTION
**Pull request by DTFUHF**
This fixes two minor bugs in SBUS input to TX.

### CODE REVIEW

**Comment by kh4** [comment]
I need to check this, I did verify sbus operation on TX side with frsky X9R. I should have time to check even today.

**Comment by arrowcircle** [comment]
@DTFUHF @kh4 Hi!
I am trying to set up retranslator 2.4 -> 433 with orange rx 1w transmitter. I set up sbus output of my x8r receiver to -, + and ppm inputs of tx/ When I power up my setup, it shows no ppm signal input. If I connect to TX with ftdi - it shows the same.
Is it possible to make sbus input for tx module? How to wire it right?

**Comment by kh4** [comment]
You need to invert the signal from X8R and feed it into the serial 'RX' pin on the TX.

The SBUS signal from X8R should work witout this patch

**Comment by arrowcircle** [comment]
@kh4 Should I move sbus wire from JR to RX of serial port (used to flash via ftdi)?

**Comment by kh4** [comment]
@arrowcircle yes, and you will also need to invert the signal.

**Comment by arrowcircle** [comment]
@kha Thank you, Do I need to make it 3.3V on RX serial? Or Only inverter is needed?

**Pull request merged**
